### ISSUE TITLE
New quest: Peak features

### ISSUE THREAD

**Issue by ServusWorld** [westnordost/StreetComplete#561]
# Where it shows up
`natural=peak` where either the `summit:cross=*` or the `summit:register=*` tag is missing (or both).

# Form
![form_peak](https://user-images.githubusercontent.com/31391499/29782252-266322ae-8c1c-11e7-8a51-e28e452f5097.png)

Two checkboxes with icons:
- [Summit register](https://www.flaticon.com/free-icon/open-book_174230)
- [Summit cross](https://www.flaticon.com/free-icon/crucifixion_263283)

(Actually, the form must be initialised so that the corresponding checkbox is already checked if one of the quested tags already exists, but it's no problem if it ignores it, then the user keeps the information latest :))

# What will be added
If the user checked "Summit cross", `summit:cross=yes` is added, else `summit:cross=no`
If the user checked "Summit register", `summit:register=yes` is added, else `summit:register=no`

# Other answers
_(no ideas so far ...)_

**Comment by matkoniecz** [comment]
Why with checkboxes rather than using style used for marking matching sports for leisure=pitch quest?

**Comment by ServusWorld** [comment]
Well, that's true.

**Comment by matkoniecz** [comment]
Main problem here is that vast majority of peaks have neither first nor second feature.

Is there way to select (by country?) peaks that are likely to have either of this features?

**Comment by rugk** [comment]
@ServusWorld Could you please use the checkboxes as indicated in the issue template? (You can still edit your issue.)

**Comment by ServusWorld** [comment]
Yes, I will do so.
(Not now, but not later than tomorrow.)

**Comment by westnordost** [comment]
Would there reasonably be a summit register and/or cross to be expected on all these peaks here?:

http://www.openstreetmap.org/#map=12/50.9042/14.2863

Are there not more properties with which this could be contained?

**Comment by ServusWorld** [comment]
At least, the quest fulfils "Applies to a reasonable number of elements (Worth the effort)" :)

Crosses maybe many of them, summit registers rather not ...

**Comment by westnordost** [comment]
1. I think it should probably be limited to certain countries where summit crosses (what about non christian countries, do they have something else?) and registers are commonplace
2. Probably it makes sense to limit this to peaks that have a name (and/or recorded height?)

**Comment by westnordost** [comment]
By the way, your icons for the mockups are nice. But generally, images or icons are only **necessary** when the text alone is not enough to convey what is being asked for. So, I think in this case (and the organic quest), nothing speaks against having simply two radio buttons.

Just saying, in case you thought this is required always.

**Comment by ServusWorld** [comment]
Requiring a name is a good idea to only quest "serious" peaks. There could also be a minimum height (I wouldn't expect one at a 500m "mountain").

I can only say about my native land (Austria) that it is quite familiar here to put a cross on a peak and summit registers aren't rare as well (I think same for whole Europe or at least Middle Europe).

But how are the conventions in totally different countries? Hard to say. (I don't even know where to research.)

**Comment by ServusWorld** [comment]
Thanks :)
I actually love icons and graphical "gadgets" and that's what Iike about StreetComplete: Not just typing something into a boring textfield, but filling it into streetsigns etc.

**Comment by rugk** [comment]
>  So, I think in this case (and the organic quest), nothing speaks against having simply two radio buttons.

But also nothing speaks against it. (As for "organic quest": Yes, there it may only be a yes/no quest as for vegan/vegetarian so that does not matter here.)
And I'd say it is quite useful to have an image there. Because I can think that some people may not instantly know what a summit register is and they can see that it is a book. In any case, visual thing *always* help. However, to be more helpful maybe a picture of the real thing, ([summit register](https://en.wikipedia.org/wiki/Summit_register#/media/File:White_Butte_Summit_Register.jpg) e.g.) may be better.
But these are all details…

The problem I see: Are not these summit registers only on popular or big summits and otherwise mostly intended for climbers? So okay, StreetComplete users may also be climbers, and if not they don't reach the quest anyway, but hmm…
I also find this idea lovely, but hmm…

A good argument against the "too many quests" I see is: In these areas with many summits/mountains, it is very likely that you don't have many other quests there anyway. So summit may be the only quests there and only in the valleys you can find some civilization and some more quests.
So they would not spam the whole UI and overlap/hide other quests.

**Comment by matkoniecz** [comment]
> I can only say about my native land (Austria) that it is quite familiar here to put a cross on a peak and summit registers aren't rare as well (I think same for whole Europe or at least Middle Europe).

In Poland crosses are quite rare (1 in 100? 1 in 1000? of mapped peaks would have one) and summit registers are extremely rare.

My very limited experience with summit registers in Austria is that in this country summit registers are quite popular.

Maybe limiting this to named peaks next to route=hiking relations would help to avoid asking about peaks far away from anything (like http://www.openstreetmap.org/?mlat=49.2306&mlon=20.0555#map=16/49.2306/20.0555)?

**Comment by ServusWorld** [comment]
Thanks, know we know it about one more country :)

Would limitation to peaks with names and a minimum height of - let's say - 800m increase the amount?

**Comment by ServusWorld** [comment]
Well, there are no other quests in the mountains yet, so the map won't get too full ...
And if no StreetCompleter climbs a quested peak, it keeps standing - that's no problem then.

**Comment by westnordost** [comment]
So what is needed:
- List of countries for which this quest should initially be visible (can be extended later)

**Comment by rugk** [comment]
I think this list can be a small whitelist. So maybe don't include Poland. :wink: 

`isSummitMarkingsKnown`
```yaml
# whether a summit register and/or summit cross is known
default: false
# source: translation of wikipedia article https://en.wikipedia.org/wiki/Summit_register
CZ: true
DE: true
ES: true
IT: true
# not including Netherlands (NL) as the wiki article on that subject is about the "foreign" summit registers in the Alps, e.g.

# source: https://it.wikipedia.org/wiki/Libro_di_vetta#Alcuni_esempi_di_libri_di_vetta
FR: true
GR: true 
SI: true

# source: common-knowledge/user-contributions for summit registers
AT: true
CH: true
 # if known in slovenia, likely also in Slovakia??

# source: https://de.wikipedia.org/wiki/Gipfelkreuz#Bildergalerie, https://en.wikipedia.org/wiki/Summit_cross#Gallery (excluding entries already included above)
AR: true

# source: https://es.wikipedia.org/wiki/Cruz_de_la_cumbre#Ejemplos (excluding entries already included above)
PE: true
# excluding PO because of user-experience (https://github.com/westnordost/StreetComplete/issues/561#issuecomment-325504455)
RO: true

# source: https://it.wikipedia.org/wiki/Croce_di_vetta#Alcuni_esempi_di_croci_di_vetta
SK: true
```
